<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\GoogleTasksDesktopWidget.Core\GoogleTasksDesktopWidget.Core.csproj" />
    <ProjectReference Include="..\..\src\GoogleTasksDesktopWidget\GoogleTasksDesktopWidget.csproj" />
  </ItemGroup>
</Project>
